<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Boundary</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>4e215132-0f44-4cb5-b765-3ca584f54580</testSuiteGuid>
   <testCaseLink>
      <guid>653b1966-51c2-4f8f-b69a-429ee54e993d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Boundary/Login_1Charachter_Username</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b5a071bb-0b3e-470f-8368-8b6665991df5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>baa39db5-7a00-4f93-bb3f-1355d8855c8e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b45893b0-53ec-42c1-b772-b4effdc341ce</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Boundary/Login_withEndSpace</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fdc32ee3-0e2c-4e6e-9493-a2c470c21d3e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c1e9de74-f646-44e4-a050-0ce4e15c81b7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>40979bfc-a4ea-4377-8381-45c8abbb8bba</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Boundary/Login_withFirstSpace</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6f280ce3-9c43-4e70-8e37-222a33b9545c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>245216e8-e1e5-4bec-aafd-355ac6a9b7f3</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
