<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Edge</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>e0810c47-4e39-4247-9506-6558c4f37835</testSuiteGuid>
   <testCaseLink>
      <guid>7a4add03-cf3f-4f5e-916e-cba84931be68</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Edge/Login_1Charachter_Password</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>39fe09da-ca1f-4fae-a3b0-d2721507fb73</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>65556694-d2e6-4f36-8ad8-72d6686b9dbb</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a90fd023-817f-402c-b250-806ecbff6c15</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Edge/Login_EmptyUsername_Password</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>11c0a22f-d880-48ed-b16b-c337902ed889</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>285ef298-0761-4b0f-aafb-95cd5edf7e9b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>dca0a761-5563-43c1-af1e-e5912902acb2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Edge/Login_PerformanceGlitch</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7688bba9-0827-4632-9c33-2e1117240bd2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>15ad4391-2418-4b56-83e2-8e6b90d908b0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e5ff142e-2189-4e95-ade0-86383b680eeb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Edge/Login_VisualUsername</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5098f7f2-691c-4375-bdca-d85e799d246e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a66b4305-6c8f-4221-a841-c9b0aeeecd81</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>90834795-2f1c-4fc1-ab18-568b462af6fe</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Edge/Login_WrongUsername_Password</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0837fc77-dc52-4d5e-87b6-37be4048fbd6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bdfca272-515a-4469-8c52-66de5c89420c</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
