<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Negative</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>a9d862dd-0f31-432a-9881-515908a7dff7</testSuiteGuid>
   <testCaseLink>
      <guid>d6c44a8d-dc4a-47be-949d-3ce41e5b51c4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Negative/Login_Blocked_User</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0e1e3174-83fd-4e09-b991-30eddafdeb7e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d3cad742-834d-4b38-ac3e-c053e44d32eb</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7781cdd9-95b6-45e4-847c-20345890cfa4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Negative/Login_Empty_Password</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c65cc966-e05e-4245-856d-b19a97559a29</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>22ea953c-a930-4cf0-9456-6e892b8a6f49</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1e98cf72-26ea-4497-ade7-4dd40cb556c9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Negative/Login_Empty_Username</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ccd211df-136a-4239-b211-93cd87bcd6d5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e0b68903-dc6d-4cea-aa2d-aef974b1a1f7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>09659547-d67c-44eb-8504-1fd48d756737</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Negative/Login_Invalid_Password</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4e2ca067-a534-4263-916c-3a27aa390f78</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d7f6ddca-9ce5-4e78-ba81-9fa77d25cb7d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>01a1022c-0b2c-4ade-b7cc-948083d17eb3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Negative/Login_Invalid_Username</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f4ae3b40-2f19-4551-a7b8-c46987f53183</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f3f555bb-0992-41aa-9c4b-77b7d9d8c966</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
